apiVersion: v1
kind: Pod
metadata:
  name: sleepypod 
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do date; sleep 13; done
    image: busybox
    name: build-observer
  restartPolicy: Always
