apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: private-ssh-repo
  namespace: cka 
type: Opaque
data:
  sshPrivateKey: $(base64 -w 0 < ${HOME}/.ssh/id_rsa)
  type: $(echo -n git | base64 -w 0)
  url:  $(echo -n git@github.com:rienkdekok/k8sbasic.git | base64 -w0)
