apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleepy-app-deployment
  labels:
    app: sleepy-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sleepy-app
  template:
    metadata:
      labels:
        app: sleepy-app
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - while true; do date; sleep 13; done
        image: busybox
        name: sleepy-app-container
      restartPolicy: Always
